{% set name = "vcpkg-tool" %}
{% set version = "2022-02-24" %}

package:
  name: {{ name|lower }}
  version: {{ version.replace('-', '.') }}

source:
  url: https://github.com/microsoft/vcpkg-tool/archive/refs/tags/{{ version }}.tar.gz
  sha256: 004d9080717d5d0ce8961af2aa1a07fd9e9fd79833a39909bb7767d9ea775566

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  run:
    - ninja
    - cmake
    - curl
    - git
    - unzip  # [unix]
    - tar    # [unix]
    - 7zip   # [win]
  run_constrained:
    - vcpkg >2020.11

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: C++ Library Manager for Windows, Linux, and MacOS

extra:
  recipe-maintainers:
    - wolfv
